builds:
- id: "kubectl-resource-bind"
  main: ./cmd/kubectl-resource-bind
  binary: bin/kubectl-resource-bind
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
archives:
- id: kubectl-resource-bind
  builds:
  - kubectl-resource-bind
  name_template: "kubectl-resource-bind_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
  mode: keep-existing

krews:
- name: bind
  ids:
  - kubectl-resource-bind
  index:
    owner: Danil-Grigorev
    name: rancher-bind
    token: "{{ .Env.GITHUB_TOKEN }}"
  description: |
    Binds API services and other cluster types into the current cluster. API services
    are CRDs that are operated by a service provider without anything by that service
    provider running in the local cluster.
  short_description: "Bind API services and other remote types into the current cluster."
  skip_upload: auto
