name: image

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: v1.21
        check-latest: true
    - uses: sigstore/cosign-installer@v3.2.0
    - name: Install ko
      run: go install github.com/google/ko@latest

    - name: Convert actor name to lowercase and store in the env
      run: |
        echo "OWNER=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Set LDFLAGS
      run: echo LDFLAGS="$(make ldflags)" | tee -a >> $GITHUB_ENV

    # Build ko from HEAD, build and push an image tagged with the commit SHA,
    # then keylessly sign it with cosign.
    - name: Publish and sign rancher-backend image
      env:
        KO_DOCKER_REPO: ghcr.io/${{ env.OWNER }}/rancher-backend
        COSIGN_EXPERIMENTAL: 'true'
      run: |
        echo "${{ github.token }}" | ko login ghcr.io --username "${{ github.actor }}" --password-stdin
        img=$(ko build --bare --platform=all -t latest -t ${{ github.sha }} -t ${{github.ref_name}} ./cmd/rancher-backend)
        echo "built ${img}"
        cosign sign ${img} \
            -a sha=${{ github.sha }} \
            -a ref=${{ github.ref }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }} \
            --yes

    - uses: actions/delete-package-versions@v3
      with:
        package-name: 'rancher-backend'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"
